pipeline {
  environment {
    registry = “akshayshikre/hellowhale”
    registryCredential = ‘dockerhubcredentials’
    dockerImage = ‘’
  }
  agent any
  stages {
    stage(‘Cloning’) {
      steps {
        checkout scm
      }
    }
    stage(‘Building’) {
      steps{
        script {
          dockerImage = docker.build registry + ":${env.BUILD_ID}"
        }
      }
    }
    stage(‘Deploy’) {
      steps{
        script {
          docker.withRegistry( ‘’, registryCredential ) {
            dockerImage.push()
          }
        }
      }
    }
  }
}
