pipeline {
  environment {
    registry = “akshayshikre/hellowhale”
    registryCredential = ‘dockerhubcredentials’
    dockerImage = ‘’
  }
  agent any
  stages {
    stage(‘Cloning’) {
      steps {
        git ‘https://github.com/akshayshikre/hellowhale.git'
      }
    }
    stage(‘Building image’) {
      steps{
        script {
          dockerImage = docker.build registry + “:$BUILD_NUMBER”
        }
      }
    }
    stage(‘Deploy Image’) {
      steps{
        script {
          docker.withRegistry( ‘’, registryCredential ) {
            dockerImage.push()
          }
        }
      }
    }
  }
}
